version: '3.8'
services:
  vitrin:
    build:
      context: ../../Client
      dockerfile: ../Docker/Dev/Dockerfile.dev
    volumes:
      - /app/node_modules
      - ../../Client:/app
  nginx:
    depends_on:
      - vitrin
    restart: always
    build: 
      context: ../../nginx/dev
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
